"""esquema inicial

Revision ID: 2e05d55241aa
Revises: 
Create Date: 2026-08-31 22:52:30.492775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e05d55241aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('intentos_login_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)

    op.create_table('etiquetas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nombre', name='uq_etiqueta_usuario_nombre')
    )
    with op.batch_alter_table('etiquetas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etiquetas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_correo', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('accion', sa.String(length=80), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('entidad_tipo', sa.String(length=30), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('direccion_ip', sa.String(length=45), nullable=True),
    sa.Column('agente_usuario', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_auditoria_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.create_index('idx_proyectos_nombre_ft', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.create_index(batch_op.f('ix_proyectos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('tokens_actualizacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('identificador_jti', sa.String(length=36), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('reemplazado_por_jti', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens_actualizacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_actualizacion_identificador_jti'), ['identificador_jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_tokens_actualizacion_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('miembros_proyecto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permiso', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proyecto_id', 'usuario_id', name='uq_miembro_proyecto_usuario')
    )
    with op.batch_alter_table('miembros_proyecto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_miembros_proyecto_proyecto_id'), ['proyecto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_miembros_proyecto_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('asignado_a_usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('completado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.create_index('idx_tareas_titulo_desc_ft', ['titulo', 'descripcion'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.create_index('idx_tareas_titulo_ft', ['titulo'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.create_index(batch_op.f('ix_tareas_asignado_a_usuario_id'), ['asignado_a_usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_proyecto_id'), ['proyecto_id'], unique=False)

    op.create_table('checklist_tarea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('esta_completado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_tarea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_tarea_tarea_id'), ['tarea_id'], unique=False)

    op.create_table('comentarios_tarea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentarios_tarea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comentarios_tarea_tarea_id'), ['tarea_id'], unique=False)

    op.create_table('registro_actividad_tarea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_actividad_tarea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_actividad_tarea_tarea_id'), ['tarea_id'], unique=False)

    op.create_table('tarea_etiquetas',
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tarea_id', 'etiqueta_id')
    )
    op.create_table('menciones_comentario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['comentarios_tarea.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comentario_id', 'usuario_id', name='uq_mencion_comentario_usuario')
    )
    with op.batch_alter_table('menciones_comentario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menciones_comentario_comentario_id'), ['comentario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menciones_comentario_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menciones_comentario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menciones_comentario_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_menciones_comentario_comentario_id'))

    op.drop_table('menciones_comentario')
    op.drop_table('tarea_etiquetas')
    with op.batch_alter_table('registro_actividad_tarea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_actividad_tarea_tarea_id'))

    op.drop_table('registro_actividad_tarea')
    with op.batch_alter_table('comentarios_tarea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comentarios_tarea_tarea_id'))

    op.drop_table('comentarios_tarea')
    with op.batch_alter_table('checklist_tarea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_tarea_tarea_id'))

    op.drop_table('checklist_tarea')
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tareas_proyecto_id'))
        batch_op.drop_index(batch_op.f('ix_tareas_asignado_a_usuario_id'))
        batch_op.drop_index('idx_tareas_titulo_ft', mysql_prefix='FULLTEXT')
        batch_op.drop_index('idx_tareas_titulo_desc_ft', mysql_prefix='FULLTEXT')

    op.drop_table('tareas')
    with op.batch_alter_table('miembros_proyecto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_miembros_proyecto_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_miembros_proyecto_proyecto_id'))

    op.drop_table('miembros_proyecto')
    with op.batch_alter_table('tokens_actualizacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_actualizacion_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_actualizacion_identificador_jti'))

    op.drop_table('tokens_actualizacion')
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proyectos_usuario_id'))
        batch_op.drop_index('idx_proyectos_nombre_ft', mysql_prefix='FULLTEXT')

    op.drop_table('proyectos')
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_creado_en'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_categoria'))

    op.drop_table('logs_auditoria')
    with op.batch_alter_table('etiquetas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etiquetas_usuario_id'))

    op.drop_table('etiquetas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
